### ISSUE TITLE
获取包 失败，xsec-evil-ips/cmd这个是哪里地址？

### ISSUE THREAD

**Issue by LastKing** [netxfly/xsec-ip-database#3]
不是github的？
xsec-evil-ips，怎么获取？

**Comment by netxfly** [comment]
这个在这个项目的cmd目录下，你编译失败的原因可能是与项目中绝对路径不同。自己根据实际情况改一下就可以了。

**Comment by imfht** [comment]
have a look at #4 
a built version can be found at [https://termbin.co/public/](https://termbin.co/public/). this built for Linux amd64
may it helps you
